// <auto-generated />
using System;
using CarsProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarsProject.Migrations
{
    [DbContext(typeof(CarsContext))]
    [Migration("20250629135908_endseedingdd")]
    partial class endseedingdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarsProject.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Condition")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Transmission")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Color = "White",
                            Condition = "New",
                            Description = "Reliable and efficient sedan.",
                            ImageUrl = "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=500&q=80",
                            Name = "Toyota Corolla 2022",
                            Price = 22000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Color = "Red",
                            Condition = "Used",
                            Description = "Classic American muscle car.",
                            ImageUrl = "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?w=500&q=80",
                            Name = "Ford Mustang 2021",
                            Price = 35000,
                            Status = "Available",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Color = "Blue",
                            Condition = "Used",
                            Description = "Compact car with great value.",
                            ImageUrl = "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=500&q=80",
                            Name = "Honda Civic 2020",
                            Price = 19000,
                            Status = "Sold",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Color = "Black",
                            Condition = "Used",
                            Description = "Luxury and performance combined.",
                            ImageUrl = "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=500&q=80",
                            Name = "BMW 3 Series 2019",
                            Price = 28000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Color = "Silver",
                            Condition = "New",
                            Description = "Elegant and high-tech sedan.",
                            ImageUrl = "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=500&q=80",
                            Name = "Mercedes C-Class 2023",
                            Price = 40000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Color = "Yellow",
                            Condition = "Used",
                            Description = "Sporty and stylish ride.",
                            ImageUrl = "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=500&q=80",
                            Name = "Chevrolet Camaro 2021",
                            Price = 33000,
                            Status = "Available",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Color = "White",
                            Condition = "New",
                            Description = "Electric sedan with autopilot.",
                            ImageUrl = "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=500&q=80",
                            Name = "Tesla Model 3 2022",
                            Price = 45000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Color = "Green",
                            Condition = "Used",
                            Description = "Compact hatchback with agility.",
                            ImageUrl = "https://images.unsplash.com/photo-1606016838648-b8e527f7daf8?w=500&q=80",
                            Name = "Volkswagen Golf 2020",
                            Price = 20000,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Color = "Blue",
                            Condition = "New",
                            Description = "Reliable midsize family sedan.",
                            ImageUrl = "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=500&q=80",
                            Name = "Nissan Altima 2021",
                            Price = 23000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Color = "Grey",
                            Condition = "Used",
                            Description = "Affordable and efficient.",
                            ImageUrl = "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=500&q=80",
                            Name = "Hyundai Elantra 2019",
                            Price = 17000,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Color = "Black",
                            Condition = "New",
                            Description = "Stylish and compact.",
                            ImageUrl = "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=500&q=80",
                            Name = "Kia Forte 2022",
                            Price = 18500,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Color = "Red",
                            Condition = "Used",
                            Description = "Fun to drive compact car.",
                            ImageUrl = "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=500&q=80",
                            Name = "Mazda 3 2021",
                            Price = 21000,
                            Status = "Available",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Color = "White",
                            Condition = "Used",
                            Description = "Spacious and dependable.",
                            ImageUrl = "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=500&q=80",
                            Name = "Toyota Camry 2020",
                            Price = 25000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Color = "Silver",
                            Condition = "New",
                            Description = "Premium interior and design.",
                            ImageUrl = "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=500&q=80",
                            Name = "Audi A4 2023",
                            Price = 39000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Color = "Blue",
                            Condition = "Used",
                            Description = "Efficient family car.",
                            ImageUrl = "https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=500&q=80",
                            Name = "Skoda Octavia 2021",
                            Price = 24000,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Color = "Red",
                            Condition = "New",
                            Description = "Sporty and agile hatchback.",
                            ImageUrl = "https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=500&q=80",
                            Name = "Seat Leon 2022",
                            Price = 23000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Color = "Grey",
                            Condition = "Used",
                            Description = "Reliable and spacious.",
                            ImageUrl = "https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=500&q=80",
                            Name = "Opel Astra 2021",
                            Price = 21000,
                            Status = "Available",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Color = "White",
                            Condition = "New",
                            Description = "Stylish compact SUV.",
                            ImageUrl = "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=500&q=80",
                            Name = "Peugeot 3008 2023",
                            Price = 32000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Color = "Black",
                            Condition = "Used",
                            Description = "Affordable hatchback.",
                            ImageUrl = "https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=500&q=80",
                            Name = "Renault Megane 2020",
                            Price = 18000,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Color = "Silver",
                            Condition = "New",
                            Description = "Safe and elegant sedan.",
                            ImageUrl = "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=500&q=80",
                            Name = "Volvo S60 2022",
                            Price = 37000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Color = "Grey",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=500&q=80",
                            Name = "Citroen C4 2016",
                            Price = 23300,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Color = "Green",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=500&q=80",
                            Name = "Jeep Grand Cherokee 2017",
                            Price = 23600,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Color = "Yellow",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=500&q=80",
                            Name = "Land Rover Discovery 2018",
                            Price = 23900,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Color = "Red",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=500&q=80",
                            Name = "Fiat Tipo 2019",
                            Price = 24200,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            Color = "Blue",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://cdn.motor1.com/images/mgl/JOA6zK/s1/mini-john-cooper-works-electric-2024.jpg",
                            Name = "Mini Cooper 2020",
                            Price = 24500,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Color = "Black",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=500&q=80",
                            Name = "Porsche Cayenne 2021",
                            Price = 24800,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Color = "White",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=500&q=80",
                            Name = "Jaguar XE 2022",
                            Price = 25100,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            Color = "Silver",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=500&q=80",
                            Name = "Ford Explorer 2023",
                            Price = 25400,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            Color = "Grey",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=500&q=80",
                            Name = "Chevy Tahoe 2024",
                            Price = 25700,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            Color = "Green",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=500&q=80",
                            Name = "Toyota Corolla 2015",
                            Price = 26000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            Color = "Yellow",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?w=500&q=80",
                            Name = "Ford Mustang 2016",
                            Price = 26300,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Color = "Red",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=500&q=80",
                            Name = "Honda Civic 2017",
                            Price = 26600,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            Color = "Blue",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=500&q=80",
                            Name = "BMW 3 Series 2018",
                            Price = 26900,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 5,
                            Color = "Black",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=500&q=80",
                            Name = "Mercedes C-Class 2019",
                            Price = 27200,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 1,
                            Color = "White",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=500&q=80",
                            Name = "Chevrolet Camaro 2020",
                            Price = 27500,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 2,
                            Color = "Silver",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=500&q=80",
                            Name = "Tesla Model 3 2021",
                            Price = 27800,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            Color = "Grey",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1606016838648-b8e527f7daf8?w=500&q=80",
                            Name = "Volkswagen Golf 2022",
                            Price = 28100,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Color = "Green",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=500&q=80",
                            Name = "Nissan Altima 2023",
                            Price = 28400,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 5,
                            Color = "Yellow",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=500&q=80",
                            Name = "Hyundai Elantra 2024",
                            Price = 28700,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 1,
                            Color = "Red",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=500&q=80",
                            Name = "Kia Forte 2015",
                            Price = 29000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 2,
                            Color = "Blue",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=500&q=80",
                            Name = "Mazda 3 2016",
                            Price = 29300,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            Color = "Black",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=500&q=80",
                            Name = "Toyota Camry 2017",
                            Price = 29600,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            Color = "White",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=500&q=80",
                            Name = "Audi A4 2018",
                            Price = 29900,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            Color = "Silver",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=500&q=80",
                            Name = "Skoda Octavia 2019",
                            Price = 30200,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 1,
                            Color = "Grey",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=500&q=80",
                            Name = "Seat Leon 2020",
                            Price = 30500,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 2,
                            Color = "Green",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=500&q=80",
                            Name = "Opel Astra 2021",
                            Price = 30800,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 3,
                            Color = "Yellow",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=500&q=80",
                            Name = "Peugeot 3008 2022",
                            Price = 31100,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            Color = "Red",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=500&q=80",
                            Name = "Renault Megane 2023",
                            Price = 31400,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            Color = "Blue",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=500&q=80",
                            Name = "Volvo S60 2024",
                            Price = 31700,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 1,
                            Color = "Black",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=500&q=80",
                            Name = "Peugeot 508 2015",
                            Price = 32000,
                            Status = "Available",
                            Transmission = "Automatic"
                        });
                });

            modelBuilder.Entity("CarsProject.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("CarsProject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hatchback"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Luxury"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("CarsProject.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CarsProject.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CarsProject.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CarsProject.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CarsProject.Models.Car", b =>
                {
                    b.HasOne("CarsProject.Models.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CarsProject.Models.CartItem", b =>
                {
                    b.HasOne("CarsProject.Models.Car", "Car")
                        .WithMany("CartItems")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarsProject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarsProject.Models.Order", b =>
                {
                    b.HasOne("CarsProject.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarsProject.Models.OrderItem", b =>
                {
                    b.HasOne("CarsProject.Models.Car", "Car")
                        .WithMany("OrderItems")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarsProject.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CarsProject.Models.Review", b =>
                {
                    b.HasOne("CarsProject.Models.Car", "Car")
                        .WithMany("Reviews")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarsProject.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CarsProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CarsProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarsProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CarsProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarsProject.Models.Car", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CarsProject.Models.Category", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarsProject.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CarsProject.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
