// <auto-generated />
using System;
using CarsProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarsProject.Migrations
{
    [DbContext(typeof(CarsContext))]
    partial class CarsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarsProject.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transmission")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Color = "White",
                            Condition = "New",
                            Description = "Reliable and efficient sedan.",
                            ImageUrl = "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
                            Name = "Toyota Corolla 2022",
                            Price = 22000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Color = "Red",
                            Condition = "Used",
                            Description = "Classic American muscle car.",
                            ImageUrl = "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
                            Name = "Ford Mustang 2021",
                            Price = 35000,
                            Status = "Available",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Color = "Blue",
                            Condition = "Used",
                            Description = "Compact car with great value.",
                            ImageUrl = "https://images.pexels.com/photos/1402787/pexels-photo-1402787.jpeg",
                            Name = "Honda Civic 2020",
                            Price = 19000,
                            Status = "Sold",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Color = "Black",
                            Condition = "Used",
                            Description = "Luxury and performance combined.",
                            ImageUrl = "https://images.pexels.com/photos/1007415/pexels-photo-1007415.jpeg",
                            Name = "BMW 3 Series 2019",
                            Price = 28000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Color = "Silver",
                            Condition = "New",
                            Description = "Elegant and high-tech sedan.",
                            ImageUrl = "https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg",
                            Name = "Mercedes C-Class 2023",
                            Price = 40000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Color = "Yellow",
                            Condition = "Used",
                            Description = "Sporty and stylish ride.",
                            ImageUrl = "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
                            Name = "Chevrolet Camaro 2021",
                            Price = 33000,
                            Status = "Available",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Color = "White",
                            Condition = "New",
                            Description = "Electric sedan with autopilot.",
                            ImageUrl = "https://images.pexels.com/photos/1402788/pexels-photo-1402788.jpeg",
                            Name = "Tesla Model 3 2022",
                            Price = 45000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Color = "Green",
                            Condition = "Used",
                            Description = "Compact hatchback with agility.",
                            ImageUrl = "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
                            Name = "Volkswagen Golf 2020",
                            Price = 20000,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Color = "Blue",
                            Condition = "New",
                            Description = "Reliable midsize family sedan.",
                            ImageUrl = "https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg",
                            Name = "Nissan Altima 2021",
                            Price = 23000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Color = "Grey",
                            Condition = "Used",
                            Description = "Affordable and efficient.",
                            ImageUrl = "https://images.pexels.com/photos/1402787/pexels-photo-1402787.jpeg",
                            Name = "Hyundai Elantra 2019",
                            Price = 17000,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Color = "Black",
                            Condition = "New",
                            Description = "Stylish and compact.",
                            ImageUrl = "https://images.pexels.com/photos/1007415/pexels-photo-1007415.jpeg",
                            Name = "Kia Forte 2022",
                            Price = 18500,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Color = "Red",
                            Condition = "Used",
                            Description = "Fun to drive compact car.",
                            ImageUrl = "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
                            Name = "Mazda 3 2021",
                            Price = 21000,
                            Status = "Available",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Color = "White",
                            Condition = "Used",
                            Description = "Spacious and dependable.",
                            ImageUrl = "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
                            Name = "Toyota Camry 2020",
                            Price = 25000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Color = "Silver",
                            Condition = "New",
                            Description = "Premium interior and design.",
                            ImageUrl = "https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg",
                            Name = "Audi A4 2023",
                            Price = 39000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Color = "Blue",
                            Condition = "Used",
                            Description = "Efficient family car.",
                            ImageUrl = "https://images.pexels.com/photos/1402788/pexels-photo-1402788.jpeg",
                            Name = "Skoda Octavia 2021",
                            Price = 24000,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Color = "Red",
                            Condition = "New",
                            Description = "Sporty and agile hatchback.",
                            ImageUrl = "https://images.pexels.com/photos/1007415/pexels-photo-1007415.jpeg",
                            Name = "Seat Leon 2022",
                            Price = 23000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Color = "Grey",
                            Condition = "Used",
                            Description = "Reliable and spacious.",
                            ImageUrl = "https://images.pexels.com/photos/1402787/pexels-photo-1402787.jpeg",
                            Name = "Opel Astra 2021",
                            Price = 21000,
                            Status = "Available",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Color = "White",
                            Condition = "New",
                            Description = "Stylish compact SUV.",
                            ImageUrl = "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
                            Name = "Peugeot 3008 2023",
                            Price = 32000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Color = "Black",
                            Condition = "Used",
                            Description = "Affordable hatchback.",
                            ImageUrl = "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
                            Name = "Renault Megane 2020",
                            Price = 18000,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Color = "Silver",
                            Condition = "New",
                            Description = "Safe and elegant sedan.",
                            ImageUrl = "https://images.pexels.com/photos/1402788/pexels-photo-1402788.jpeg",
                            Name = "Volvo S60 2022",
                            Price = 37000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Color = "Grey",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/1007415/pexels-photo-1007415.jpeg",
                            Name = "Citroen C4 2016",
                            Price = 23300,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Color = "Green",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg",
                            Name = "Jeep Grand Cherokee 2017",
                            Price = 23600,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Color = "Yellow",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/1402788/pexels-photo-1402788.jpeg",
                            Name = "Land Rover Discovery 2018",
                            Price = 23900,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Color = "Red",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
                            Name = "Fiat Tipo 2019",
                            Price = 24200,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            Color = "Blue",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
                            Name = "Mini Cooper 2020",
                            Price = 24500,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Color = "Black",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/1402787/pexels-photo-1402787.jpeg",
                            Name = "Porsche Cayenne 2021",
                            Price = 24800,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Color = "White",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/1007415/pexels-photo-1007415.jpeg",
                            Name = "Jaguar XE 2022",
                            Price = 25100,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            Color = "Silver",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg",
                            Name = "Ford Explorer 2023",
                            Price = 25400,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            Color = "Grey",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/1402788/pexels-photo-1402788.jpeg",
                            Name = "Chevy Tahoe 2024",
                            Price = 25700,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            Color = "Green",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
                            Name = "Toyota Corolla 2015",
                            Price = 26000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            Color = "Yellow",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
                            Name = "Ford Mustang 2016",
                            Price = 26300,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Color = "Red",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/1402787/pexels-photo-1402787.jpeg",
                            Name = "Honda Civic 2017",
                            Price = 26600,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            Color = "Blue",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/1007415/pexels-photo-1007415.jpeg",
                            Name = "BMW 3 Series 2018",
                            Price = 26900,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 5,
                            Color = "Black",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg",
                            Name = "Mercedes C-Class 2019",
                            Price = 27200,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 1,
                            Color = "White",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/1402788/pexels-photo-1402788.jpeg",
                            Name = "Chevrolet Camaro 2020",
                            Price = 27500,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 2,
                            Color = "Silver",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
                            Name = "Tesla Model 3 2021",
                            Price = 27800,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            Color = "Grey",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
                            Name = "Volkswagen Golf 2022",
                            Price = 28100,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Color = "Green",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/1402787/pexels-photo-1402787.jpeg",
                            Name = "Nissan Altima 2023",
                            Price = 28400,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 5,
                            Color = "Yellow",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/1007415/pexels-photo-1007415.jpeg",
                            Name = "Hyundai Elantra 2024",
                            Price = 28700,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 1,
                            Color = "Red",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg",
                            Name = "Kia Forte 2015",
                            Price = 29000,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 2,
                            Color = "Blue",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/1402788/pexels-photo-1402788.jpeg",
                            Name = "Mazda 3 2016",
                            Price = 29300,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            Color = "Black",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
                            Name = "Toyota Camry 2017",
                            Price = 29600,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            Color = "White",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
                            Name = "Audi A4 2018",
                            Price = 29900,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            Color = "Silver",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/1402787/pexels-photo-1402787.jpeg",
                            Name = "Skoda Octavia 2019",
                            Price = 30200,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 1,
                            Color = "Grey",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/1007415/pexels-photo-1007415.jpeg",
                            Name = "Seat Leon 2020",
                            Price = 30500,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 2,
                            Color = "Green",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg",
                            Name = "Opel Astra 2021",
                            Price = 30800,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 3,
                            Color = "Yellow",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/1402788/pexels-photo-1402788.jpeg",
                            Name = "Peugeot 3008 2022",
                            Price = 31100,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            Color = "Red",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
                            Name = "Renault Megane 2023",
                            Price = 31400,
                            Status = "Available",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            Color = "Blue",
                            Condition = "Used",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
                            Name = "Volvo S60 2024",
                            Price = 31700,
                            Status = "Sold",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 1,
                            Color = "Black",
                            Condition = "New",
                            Description = "High quality vehicle.",
                            ImageUrl = "https://images.pexels.com/photos/1402787/pexels-photo-1402787.jpeg",
                            Name = "Peugeot 508 2015",
                            Price = 32000,
                            Status = "Available",
                            Transmission = "Automatic"
                        });
                });

            modelBuilder.Entity("CarsProject.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 4,
                            Quantity = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CarId = 15,
                            Quantity = 2,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("CarsProject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hatchback"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Luxury"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("CarsProject.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            OrderDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("CarsProject.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 5,
                            OrderId = 1,
                            Price = 30000,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            CarId = 10,
                            OrderId = 1,
                            Price = 17000,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            CarId = 20,
                            OrderId = 2,
                            Price = 37000,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("CarsProject.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            Content = "Great car!",
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            Content = "Smooth ride",
                            Rating = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            Content = "Worth the price",
                            Rating = 4,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("CarsProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            Password = "admin123",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "aya@example.com",
                            Password = "aya123",
                            UserName = "aya"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mohamed@example.com",
                            Password = "mohe123",
                            UserName = "mohamed"
                        });
                });

            modelBuilder.Entity("CarsProject.Models.Car", b =>
                {
                    b.HasOne("CarsProject.Models.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CarsProject.Models.CartItem", b =>
                {
                    b.HasOne("CarsProject.Models.Car", "Car")
                        .WithMany("CartItems")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarsProject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarsProject.Models.Order", b =>
                {
                    b.HasOne("CarsProject.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarsProject.Models.OrderItem", b =>
                {
                    b.HasOne("CarsProject.Models.Car", "Car")
                        .WithMany("OrderItems")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarsProject.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CarsProject.Models.Review", b =>
                {
                    b.HasOne("CarsProject.Models.Car", "Car")
                        .WithMany("Reviews")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarsProject.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarsProject.Models.Car", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CarsProject.Models.Category", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarsProject.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CarsProject.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
